# azure-pipelines-python-sample-vscode-flask-tutorial.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      python trial.py
    displayName: 'Run Python Script'

  - script: |
      echo "Triggering React Memory Game Pipeline..."
    displayName: 'Trigger React Memorygame Pipeline'