trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: PipelineA
      project: 'bhanuproject'
      source: 'PYFL_FE'
    - pipeline: PipelineB
      project: 'bhanuproject'
      source: 'PYFL_BE'
    - pipeline: PipelineC
      project: 'bhanuproject'
      source: 'PYFL_PAYMENT'
    - pipeline: PipelineD
      project: 'bhanuproject'
      source: 'PYFL_DB'

steps:
  - template: azure-pipelines.yml

