# azure-pipelines-python-sample-vscode-flask-tutorial.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      python trial.py
    displayName: 'Run Python Script'

  - script: |
      echo "Triggering React Memory Game Pipeline..."
    displayName: 'Trigger React Memorygame Pipeline'

  - task: Bash@3
    displayName: 'Trigger Pipeline B'
    inputs:
      targetType: 'inline'
      script: |
        echo "Triggering Pipeline B..."
        curl -X POST \
          -u $(System.AccessToken): \
          -H "Content-Type: application/json" \
          --data '{"resources": {}}' \
          https://dev.azure.com/bhanupragnya/bhanuproject/_apis/pipelines/6/runs?api-version=6.0-preview.1